apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend      # This service type mentioned in api calling in frontend vite.config.js file
  namespace: devboard
  labels:
    app: devboard-backend 

spec:
  replicas: 1
  selector:
    matchLabels:
      app: devboard-backend

  template:
    metadata:
      labels:
        app: devboard-backend

    spec:
      containers:
      - name: devboard-backend-application
        image: pawarpranav/devboard-backen:v1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      

        env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: devboard-secrets
                  key: POSTGRES_DB
              
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: configmapfile-devboard
                  key: BACKEND_PORT

            - name : POSTGRES_URL
              value : postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable


                #       livenessProbe:
                #      httpGet:
                # path: /health
                # port: 8080
                # initialDelaySeconds: 25
                # periodSeconds: 15

                #   readinessProbe:
                #    httpGet:
                #     path: /health
                #     port: 8080
                #       initialDelaySeconds: 20
                #       periodSeconds: 15


