apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistant-pvc
  namespace: devboard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 500Mi