# This is the main file and all workflow call from here 
name : devsecops 
on :
    push: 
        branches: feature/CI

jobs:
  first-code-quality-check-code : 
    uses: ./.github/workflows/Code-quality-check.yml

  second-check-secerete-leaks-gitleaks : 
    uses: ./.github/workflows/Secreate-scan.yml
  
  thired-dependancy-scan : 
    uses : ./.github/workflows/Dependancy-check.yml

  Buildstage-Docker-scan-hardolint-trivy-scan : 
    uses: ./.github/workflows/Docker-scan.yml
    secrets: inherit

      #  Sonarqube-scan-code:
      #   uses: ./.github/workflows/Sonarqube-scan.yml
      #    secrets: inherit
    
  Code-Testing-stage : 
    uses: ./.github/workflows/Code-Testing.yml

  Docker-build-push-stage:
    needs: [first-code-quality-check-code, second-check-secerete-leaks-gitleaks, thired-dependancy-scan, Buildstage-Docker-scan-hardolint-trivy-scan, Sonarqube-scan-code, Code-Testing-stage]
    uses: ./.github/workflows/Docker-Build-push.yml
    secrets: inherit

# ------- CD ------

  Docker-deploye-code:
    needs: [Docker-build-push-stage]
    uses: ./.github/workflows/Code-deploy.yml
    secrets: inherit 
