# this will check your code in sonarqube 
name : sonar-qube
on : 
    workflow_call: 
jobs : 
    code-scan-by-sonarqube :
        runs-on: self-hosted
        steps:
            - name : code checkout 
              uses: actions/checkout@v7

            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v8.2.1
              env : 
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL : ${{ secrets.SONAR_HOST_URL }}

